### ISSUE TITLE
Ensure pip install and "About this notebook" cells are consistent within notebooks

### ISSUE THREAD

**Issue by bsipocz** [Caltech-IPAC/irsa-tutorials#12]
Long term it maybe nice to add a CI job to check for these, but for now, we just need to check manually that each notebook has a cell at the top with a commented out `pip install` line listing its dependencies, and also contain a last cell with author/update/irsahelp information.

- [x] install cell
- [x] author
- [x] update
- [x] irsahelp, it should be a working link not just normal text

**Comment by troyraen** [comment]
Thanks for this checklist. Do we have more things like this that we want to keep consistent across notebooks? I think there's some formatting things like making sure markdown header levels always increase/decrease by one and that section titles are not numbered. Would it be helpful to open a more general issue with a checklist of these things?

**Comment by bsipocz** [comment]
> I think there's some formatting things like making sure markdown header levels always increase/decrease by one and that section titles are not numbered. Would it be helpful to open a more general issue with a checklist of these things?

- Extreme markdown header level inconsistencies will break the build, so I think that first point works without explicit templating.

- For the right hand side TOC, I best like your cloud notebooks. They have short headings, and numbering too. I suppose we can auto generate the numbering, but doing it by hand would work, too. Would be nice to template it as right now we have at least 3 different approaches we do.

- yep, a separate issue would be good, or a template PR, maybe in the ipac-sp repo?
